---
Name: toastblocks
---

Page:
  extensions:
    - Toast\Blocks\Extensions\PageExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Toast\Blocks\Extensions\SiteConfigExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Toast\Blocks\Extensions\SiteTreeExtension

Toast\Blocks\Extensions\SiteTreeExtension:
  custom_anchors: []

Toast\Blocks\Extensions\PageExtension:
  available_blocks:
    - Toast\Blocks\TextBlock

SilverStripe\Admin\LeftAndMain:
  extensions:
    - Toast\Blocks\Extensions\LeftAndMainExtension

SilverStripe\Assets\File:
  extensions:
    - Toast\Blocks\Extensions\FileExtension

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    CmsActionsExtension: Toast\Blocks\Extensions\CmsActionsExtension

SilverStripe\LinkField\Models\Link:
  extensions:
    - Toast\Blocks\Extensions\LinkExtension

# Toast\Blocks\AccordionBlock:
#   block-icon: '[resources]/toastnz/blocks-layouts/client/images/block-icons/accordion.svg'
